name: flatppuccin
wallpapers:
  - author_name: AdalZanabria
    author_url: https://github.com/AdalZanabria
    image_url: flatppuccin_4k_macchiato_inverted.png
    modified: false
  - author_name: AdalZanabria
    author_url: https://github.com/AdalZanabria
    image_url: flatppuccin_4k_macchiato.png
    modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_blue.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_blue.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_flamingo.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_flamingo.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_green.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_green.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_lavender.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_lavender.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_maroon.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_maroon.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_mauve.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_mauve.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_peach.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_peach.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_pink.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_pink.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_red.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_red.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_rosewater.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_rosewater.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_sapphire.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_sapphire.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_sky.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_sky.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_teal.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_teal.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_frappe_yellow.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_macchiato_yellow.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_blue.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_blue.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_flamingo.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_flamingo.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_green.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_green.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_lavender.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_lavender.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_maroon.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_maroon.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_mauve.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_mauve.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_peach.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_peach.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_pink.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_pink.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_red.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_red.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_rosewater.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_rosewater.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_sapphire.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_sapphire.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_sky.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_sky.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_teal.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_teal.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_latte_yellow.png
  modified: false
  - author_name: thismoon
  author_url: https://github.com/thismoon
  image_url: flatppuccin_4k_mocha_yellow.png
  modified: false